config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'

  resources :likes, only: [:create, :destroy]
  resources :comments

devise_scope :user do
  get '/users', to: 'devise/registrations#new'
  get '/users/password', to: 'devise/passwords#new'
  get '/users/sign_out' => 'devise/sessions#destroy'
end

  
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  

  resources :users, only: [:show]

  get 'home/about'
  get 'posts/myposts'
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true, length: { minimum: 5, maximum: 500 }
  validates :keyword, presence: true, length: { minimum: 5, maximum: 100 }

  has_many_attached :images

  belongs_to :user
  has_many :comments

  has_many :likes

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  #below,If the user is not authenticated then it works expect the index ,show functions
  before_action :authenticate_user!,except: [:index, :show]
  include Pagy::Backend

  def index
    # Fetch all posts, ordered by created_at in ascending order
    
    @posts = Post.order(:created_at => :asc)
  
    # Debugging output before pagination
    puts "Total Posts Count: #{@posts.count}"
  
    # Initialize Pagy for pagination, limiting to 1 post per page

    @pagy, @posts = pagy(@posts, limit: 2)
  
    # Debugging output after pagination
    puts "Posts After Pagy: #{@posts.count}"
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  def show
    #Post 
    @comment = @post.comments.build
  end
 
  
  # GET /posts/new
  def new
    @post = Post.new
  end
  def myposts
   
    @posts = Post.all
  end
  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    puts "Post Params: #{post_params.inspect}"
    puts "Post ID: #{@post.id}"  # This should be nil for a new record
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end


    # Only allow a list of trusted parameters through.below the post model permits the title,description and keyword
    def post_params
      params.require(:post).permit(:title, :description, :keyword, :user_id, images: [])
    end
end
                                                                                  

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="col-xl-4 col-md-6 col-sm-8 col-10" style="margin:auto;background-color:#f8f8f8;border-radius: 6px; padding:15px"> 
<%= form_with(model: post) do |form| %>
<h1>New post</h1>

 

  <div>
    <% invalid = post.errors.include?(:title)%>
    <%= form.label :title, style: "display: block" %>
        <%= form.text_field :user_id , type: 'hidden' , value: current_user.id %>

    <%= form.text_field :title , class:'form-control' %>
  
    <%if invalid %>
    <p style='color:red';>
      <%= post.errors.full_messages_for(:title).join(" ,") %>
    </p >
    <% end%>
  </div>
  <div>
    <% invalid = post.errors.include?(:description)%>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description , class:'form-control'%>
    <%if invalid %>
    <p style='color:red';>
      <%= post.errors.full_messages_for(:description).join(" ,") %>
    </p>
    <% end%>
  </div>

  <div>
    <% invalid = post.errors.include?(:keyword)%>
    <%= form.label :keyword, style: "display: block" %>
    <%= form.text_field :keyword , class:'form-control' %>
    <%if invalid %>
    <p style='color:red';>
      <%= post.errors.full_messages_for(:keyword).join(" ,") %>
    </p>
    <% end%>
  </div>
<%= form.file_field :images,multiple:true%>
  <div>
    <%= form.submit class:'btn btn-primary col-12 mt-4 ' %>
  </div>
<% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class='post-container'>
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

  <p>
    <strong>Keyword:</strong>
    <%= post.keyword %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= post.user.email %>
  </p>
<%if user_signed_in? %>
<% like = current_user.likes.find_by(post: post)%>

<% if like.nil? %>
 <%= button_to 'like', likes_path, params: { like: { post_id: post.id }}, method: :post%>
<% else %> 
  <%= button_to 'unlike', like_path(like), method: :delete%>
<%end%>
<%end%>
 <%= post.likes.count%> Likes
  <% post.images.each do |image| %>
    <%= image_tag(image , style:"object-fit :cover; width: 250px; height: 600px;")  %>
  <% end %>



</div>
<p>
      <%= link_to post.user.email, post.user , style:'z-index:';%>
    </p>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag("post")%>
<p style="color: green"><%= notice %></p>
<%if user_signed_in? %>
  <%if current_user.admin?%>
  You are an admin
  <%end%>
<%end%>
<h1>Posts</h1>



<%= raw pagy_bootstrap_nav(@pagy)%>
<div id="posts" class="text-center">
  <% @posts.each do |post| %>
    <%= render post %>
   
  <% end %>
</div>

<% if user_signed_in? %>
<%= link_to "New post", new_post_path %>
<%end%>

app/views/posts/index.turbo_stream.erb
<%= turbo_stream.append :posts do %>
    <% @posts.each do |post| %>
    <% if user_signed_in? %>
    <%= render post%>
    <%end%>
    <%end%>
    <%end%>
<% if @pagy.next.present? %>
<%= turbo_stream.replace :pagination do %>
<%= turbo_frame_tag :paginaton, loading: :lazy, src: posts_path(format: :turbo_stream, page: @pagy.next)%>
<%end%>
<%end%>

app/views/posts/myposts.html.erb
<div id="posts" class="text-center">
  <% if @posts.present? %>
    <% @posts.each do |post| %>
       <% if post.user.id == current_user.id %>
      <%= render post %>
       <%end%>
    <% end %>
  <% else %>
    <p>No posts available.</p>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
<%= render "form", post: @post %>
</div>
<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>
<%if user_signed_in? %>
<%if current_user.id == @post.user.id%>
<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>
<%end%>
<%end%>

<%= render "comments/form" , comment: @comment %>

<% @post.comments.each do | comment |%>
 <% comment.text%>
 <br/>

<%end%>