config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'

  resources :likes, only: [:create, :destroy]
  resources :comments

devise_scope :user do
  get '/users', to: 'devise/registrations#new'
  get '/users/password', to: 'devise/passwords#new'
  get '/users/sign_out' => 'devise/sessions#destroy'
end

  
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  

  resources :users, only: [:show]

  get 'home/about'
  get 'posts/myposts'
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  root "posts#index"
end

app/views/layouts/_footer.html.erb
<section class="">
  <!-- Footer -->
  <footer class="text-center text-white" style="background-color: #0a4275;">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: CTA -->
      <section class="">
        <p class="d-flex justify-content-center align-items-center">
          <span class="me-3">Register for free</span>
          <button data-mdb-ripple-init type="button" class="btn btn-outline-light btn-rounded">
            Sign up!
          </button>
        </p>
      </section>
      <!-- Section: CTA -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</section>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
     <%= link_to "Home", root_path , class:'navbar-brand' , style:'margin-left:20px;'  %>
       
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup" style='margin-left:20px;'>
    <div class="navbar-nav" style='width:100%;justify-content:right;'>
      <a class="nav-link active" href="#">
   
        </a>

 
     <li class='nav-item'>
      <%= link_to "About page" , home_about_path ,class:'nav-link'%>
      </li>

  <% if user_signed_in? %>
                    <li class='nav-item'>
      <%= link_to "View my profile"  , current_user ,class:'nav-link'%>
      </li>
  
    <%= link_to "Upload Post", new_post_path, class:'nav-link'%>
         <li class='nav-item'>

      <%= link_to "Sign Out"  , destroy_user_session_path ,class:'nav-link'%>
      </li>
             <li class='nav-item'>
      <%= link_to "Edit Account"  , edit_user_registration_path ,class:'nav-link' %>
      </li>
               <li class='nav-item'>
      <%= link_to "View my posts"  , posts_myposts_path ,class:'nav-link' %>
      </li>
  <% else%>
         <li class='nav-item'>
      <%= link_to "Sign Up" , new_user_registration_path ,class:'nav-link'%>
      </li>
  <%end%>
    <%= form_with url: profiles_index_path, method: :get do |form| %>
  <div class="form-group" style='display:flex;gap:10px;margin-top:5px;margin-left:20%;'>
    <%= form.search_field :query, value: params[:query], placeholder: 'Search', class: 'search-field form-control' %>
    <%= form.submit "Search", class: 'btn btn-primary' %>
  </div>

 <%end%>
 
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%=  render "layouts/navbar"%>
    <%= yield %>
    <p class='notice'><%= notice%></p>
    <p class='alert'><%= alert %> </p>
    <%= render "layouts/footer"%>
  </body>
</html>